### ISSUE TITLE
The trained_models connt be loaded

### ISSUE THREAD

**Issue by liudapeng2333** [zahid58/TwoStreamSepConvLSTM_ViolenceDetection#6]
There was an error when I loaded the training model 

![1623072732(1)](https://user-images.githubusercontent.com/61301194/121025672-fd824080-c7d7-11eb-8f7f-7377d9877023.png)

**Comment by Zedd1558** [comment]
there was a mistake in trained_model_path in the how to run part of readme, i fixed it.
I ran the following snippet on tf 2.5.0 which gave no error.  please try the following snippet to load the model and evaluate and let me know if there was any error.

#### run evaluate.py on trained_models
The trained models weigths are available in the drive folder [trained_models](https://drive.google.com/drive/folders/1igx-plktW069IgXyWg3H78AKuTg-jCza?usp=sharing). Copy the model you want to use into your project directory like shown below. Then you can evaluate the trained_model like below.

![trained_model_evaluate](https://github.com/Zedd1558/TwoStreamSepConvLSTM_ViolenceDetection/blob/master/imgs/3.png)

```
python evaluate.py --dataset rwf2000 --vidLen 32 --batchSize 4 --mode both --lstmType sepconv --fusionType M --weightsPath "/content/violenceDetection/model/rwf2000_model"
```
